swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
        - User accounts
      summary: API to view user account balances
      description: balance of the user accounts
      parameters:
        - name: accounts
          in: body
          description: View user accounts
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: account balance user retrieved Successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/accountId:
    get:
      tags:
        - User accounts
      summary: displays the accountId balance selected by the user in another view
      description: balance of the user accountId
      parameters:
        - name: accounts
          in: body
          description: View user accounts
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: accountId balance user retrieved Successfully
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/accountId/transactions:
    get:
      tags:
        - transaction
      summary: transaction details
      description: View user account transactions
      parameters:
        - name: transactionId
          in: body
          description: transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User transaction details retrieved Successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/accountId/transactions/transactionId:
    put:
      tags:
        - transaction
      summary: add details
      description: add details to a transaction
      parameters:
        - name: transactionId
          in: body
          description: Update details transactionId
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: details successfully added
          schema:
            $ref: "#/definitions/TransactionType"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      tags:
        - transaction
      summary: delete details
      description: Delete details transactionId
      parameters:
        - name: transactionId
          in: body
          description:
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: details successfully deleted
          schema:
            $ref: "#/definitions/TransactionType"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Account:
    properties:
      id_account:
        type: number
        description: ID user account
      title:
        type: string
        description: account title
      balance:
        type: number
        description: balance of the owner account
      currency:
        type: string
        description: country currency
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          id_account:
            type: string
            description: ID user account
          title:
            type: string
            description: account title
          balance:
            type: number
            description: balance of the owner account
          currency:
            type: string
            description: country currency
  Transaction:
    type: object
    properties:
      id_transaction:
        type: number
        description: single transaction
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: description of the transaction carried out
      amount:
        type: number
        description: amount transaction
  TransactionType:
    type: object
    properties:
      category:
        type: string
        description: user to edit to a select dropdown
      notes:
        type: string
        description: user to add notes via test input
